In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('Bias_correction_ucl.csv')

In [3]:
df.head()

,station,Date,Present_Tmax,Present_Tmin,LDAPS_RHmin,LDAPS_RHmax,LDAPS_Tmax_lapse,LDAPS_Tmin_lapse,LDAPS_WS,LDAPS_LH,...,LDAPS_PPT2,LDAPS_PPT3,LDAPS_PPT4,lat,lon,DEM,Slope,Solar radiation,Next_Tmax,Next_Tmin
0,1.0,2013-06-30,28.7,21.4,58.255688,91.116364,28.074101,23.006936,6.818887,69.451805,...,0.0,0.0,0.0,37.6046,126.991,212.3350,2.7850,5992.895996,29.1,21.2
1,2.0,2013-06-30,31.9,21.6,52.263397,90.604721,29.850689,24.035009,5.691890,51.937448,...,0.0,0.0,0.0,37.6046,127.032,44.7624,0.5141,5869.312500,30.5,22.5
2,3.0,2013-06-30,31.6,23.3,48.690479,83.973587,30.091292,24.565633,6.138224,20.573050,...,0.0,0.0,0.0,37.5776,127.058,33.3068,0.2661,5863.555664,31.1,23.9
3,4.0,2013-06-30,32.0,23.4,58.239788,96.483688,29.704629,23.326177,5.650050,65.727144,...,0.0,0.0,0.0,37.6450,127.022,45.7160,2.5348,5856.964844,31.7,24.3
4,5.0,2013-06-30,31.4,21.9,56.174095,90.155128,29.113934,23.486480,5.735004,107.965535,...,0.0,0.0,0.0,37.5507,127.135,35.0380,0.5055,5859.552246,31.2,22.5

In [4]:
df.shape

(7752, 25)

In [5]:
df.isnull().sum()

station              2
Date                 2
Present_Tmax        70
Present_Tmin        70
LDAPS_RHmin         75
LDAPS_RHmax         75
LDAPS_Tmax_lapse    75
LDAPS_Tmin_lapse    75
LDAPS_WS            75
LDAPS_LH            75
LDAPS_CC1           75
LDAPS_CC2           75
LDAPS_CC3           75
LDAPS_CC4           75
LDAPS_PPT1          75
LDAPS_PPT2          75
LDAPS_PPT3          75
LDAPS_PPT4          75
lat                  0
lon                  0
DEM                  0
Slope                0
Solar radiation      0
Next_Tmax           27
Next_Tmin           27
dtype: int64

In [6]:
df['Date'].unique()

array(['2013-06-30', '2013-07-01', '2013-07-02', '2013-07-03',
       '2013-07-04', '2013-07-05', '2013-07-06', '2013-07-07',
       '2013-07-08', '2013-07-09', '2013-07-10', '2013-07-11',
       '2013-07-12', '2013-07-13', '2013-07-14', '2013-07-15',
       '2013-07-16', '2013-07-17', '2013-07-18', '2013-07-19',
       '2013-07-20', '2013-07-21', '2013-07-22', '2013-07-23',
       '2013-07-24', '2013-07-25', '2013-07-26', '2013-07-27',
       '2013-07-28', '2013-07-29', '2013-07-30', '2013-07-31',
       '2013-08-01', '2013-08-02', '2013-08-03', '2013-08-04',
       '2013-08-05', '2013-08-06', '2013-08-07', '2013-08-08',
       '2013-08-09', '2013-08-10', '2013-08-11', '2013-08-12',
       '2013-08-13', '2013-08-14', '2013-08-15', '2013-08-16',
       '2013-08-17', '2013-08-18', '2013-08-19', '2013-08-20',
       '2013-08-21', '2013-08-22', '2013-08-23', '2013-08-24',
       '2013-08-25', '2013-08-26', '2013-08-27', '2013-08-28',
       '2013-08-29', '2013-08-30', '2014-06-30', '2014-07-01',
       '2014-07-02', '2014-07-03', '2014-07-04', '2014-07-05',
       '2014-07-06', '2014-07-07', '2014-07-08', '2014-07-09',
       '2014-07-10', '2014-07-11', '2014-07-12', '2014-07-13',
       '2014-07-14', '2014-07-15', '2014-07-16', '2014-07-17',
       '2014-07-18', '2014-07-19', '2014-07-20', '2014-07-21',
       '2014-07-22', '2014-07-23', '2014-07-24', '2014-07-25',
       '2014-07-26', '2014-07-27', '2014-07-28', '2014-07-29',
       '2014-07-30', '2014-07-31', '2014-08-01', '2014-08-02',
       '2014-08-03', '2014-08-04', '2014-08-05', '2014-08-06',
       '2014-08-07', '2014-08-08', '2014-08-09', '2014-08-10',
       '2014-08-11', '2014-08-12', '2014-08-13', '2014-08-14',
       '2014-08-15', '2014-08-16', '2014-08-17', '2014-08-18',
       '2014-08-19', '2014-08-20', '2014-08-21', '2014-08-22',
       '2014-08-23', '2014-08-24', '2014-08-25', '2014-08-26',
       '2014-08-27', '2014-08-28', '2014-08-29', '2014-08-30',
       '2015-06-30', '2015-07-01', '2015-07-02', '2015-07-03',
       '2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
       '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
       '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15',
       '2015-07-16', '2015-07-17', '2015-07-18', '2015-07-19',
       '2015-07-20', '2015-07-21', '2015-07-22', '2015-07-23',
       '2015-07-24', '2015-07-25', '2015-07-26', '2015-07-27',
       '2015-07-28', '2015-07-29', '2015-07-30', '2015-07-31',
       '2015-08-01', '2015-08-02', '2015-08-03', '2015-08-04',
       '2015-08-05', '2015-08-06', '2015-08-07', '2015-08-08',
       '2015-08-09', '2015-08-10', '2015-08-11', '2015-08-12',
       '2015-08-13', '2015-08-14', '2015-08-15', '2015-08-16',
       '2015-08-17', '2015-08-18', '2015-08-19', '2015-08-20',
       '2015-08-21', '2015-08-22', '2015-08-23', '2015-08-24',
       '2015-08-25', '2015-08-26', '2015-08-27', '2015-08-28',
       '2015-08-29', '2015-08-30', '2016-06-30', '2016-07-01',
       '2016-07-02', '2016-07-03', '2016-07-04', '2016-07-05',
       '2016-07-06', '2016-07-07', '2016-07-08', '2016-07-09',
       '2016-07-10', '2016-07-11', '2016-07-12', '2016-07-13',
       '2016-07-14', '2016-07-15', '2016-07-16', '2016-07-17',
       '2016-07-18', '2016-07-19', '2016-07-20', '2016-07-21',
       '2016-07-22', '2016-07-23', '2016-07-24', '2016-07-25',
       '2016-07-26', '2016-07-27', '2016-07-28', '2016-07-29',
       '2016-07-30', '2016-07-31', '2016-08-01', '2016-08-02',
       '2016-08-03', '2016-08-04', '2016-08-05', '2016-08-06',
       '2016-08-07', '2016-08-08', '2016-08-09', '2016-08-10',
       '2016-08-11', '2016-08-12', '2016-08-13', '2016-08-14',
       '2016-08-15', '2016-08-16', '2016-08-17', '2016-08-18',
       '2016-08-19', '2016-08-20', '2016-08-21', '2016-08-22',
       '2016-08-23', '2016-08-24', '2016-08-25', '2016-08-26',
       '2016-08-27', '2016-08-28', '2016-08-29', '2016-08-30',
       '2017-06-30', '2017-07-01', '2017-07-02', '2017-07-03',
       '2017-07-04', '2017-07-05', '2017-07-06', '2017-07-07',
       '2017-07-08', '2017-07-09', '2017-07-10', '2017-07-11',
       '2017-07-12', '2017-07-13', '2017-07-14', '2017-07-15',
       '2017-07-16', '2017-07-17', '2017-07-18', '2017-07-19',
       '2017-07-20', '2017-07-21', '2017-07-22', '2017-07-23',
       '2017-07-24', '2017-07-25', '2017-07-26', '2017-07-27',
       '2017-07-28', '2017-07-29', '2017-07-30', '2017-07-31',
       '2017-08-01', '2017-08-02', '2017-08-03', '2017-08-04',
       '2017-08-05', '2017-08-06', '2017-08-07', '2017-08-08',
       '2017-08-09', '2017-08-10', '2017-08-11', '2017-08-12',
       '2017-08-13', '2017-08-14', '2017-08-15', '2017-08-16',
       '2017-08-17', '2017-08-18', '2017-08-19', '2017-08-20',
       '2017-08-21', '2017-08-22', '2017-08-23', '2017-08-24',
       '2017-08-25', '2017-08-26', '2017-08-27', '2017-08-28',
       '2017-08-29', '2017-08-30', nan], dtype=object)

In [7]:
df['Date'].value_counts()

2017-08-25    25
2013-08-28    25
2014-08-05    25
2016-06-30    25
2014-08-24    25
              ..
2013-08-16    25
2017-07-13    25
2013-07-23    25
2014-08-09    25
2016-07-14    25
Name: Date, Length: 310, dtype: int64

In [13]:
df['station'].value_counts()

25.0    310
12.0    310
2.0     310
3.0     310
4.0     310
5.0     310
6.0     310
7.0     310
8.0     310
9.0     310
10.0    310
11.0    310
13.0    310
23.0    310
14.0    310
15.0    310
16.0    310
18.0    310
20.0    310
22.0    310
24.0    310
17.0    310
19.0    310
21.0    310
1.0     310
Name: station, dtype: int64

In [12]:
df['station'].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., nan])